name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "Latihan-CI/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo $CSV_URL

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Run mlflow project
        run: |
          mlflow run Latihan-CI --env-manager=local

      # SELESAI TRAINING, LANGSUNG UPLOAD KE GOOGLE DRIVE
      - name: Upload hasil ke Google Drive
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          python upload_drive.py
